// 예시 전용: 메모리에서만 변경, API 및 운영 데이터 저장 없음.
(()=>{
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const types=['DR 등록','매출','부킹','신규 파트너','교육 이수','직접 입력'],units=['건','K USD','개사','명'];
const presets={'DR 등록':['건','기간 내 승인된 DR 기준'],'매출':['K USD','기간 내 매출 인식 기준'],'부킹':['K USD','기간 내 부킹 확정 기준'],'신규 파트너':['개사','기간 내 신규 계약 완료 기준'],'교육 이수':['명','기간 내 교육 이수 완료 기준']};
let promos=[{name:'신규 파트너 첫 딜 등록',start:'2026-09-01',end:'2026-10-31',scheme:'첫 승인 DR당 0.05 K USD · 파트너당 1회',goals:[{type:'DR 등록',unit:'건',target:20,actual:12,rule:'기간 내 승인된 DR 기준',source:'직접 입력'}]}, {name:'분기 매출 확대',start:'2026-09-01',end:'2026-10-15',scheme:'대상 제품 매출 조건 충족 시 리워드 지급',goals:[{type:'매출',unit:'K USD',target:100,actual:110,rule:'취소·반품 제외 순매출 · 인식일 기준',source:'ERP 연동'}]}, {name:'DR에서 부킹까지',start:'2026-09-01',end:'2026-10-31',scheme:'DR 승인당 보상 지급 · 부킹 목표와 별도',goals:[{type:'DR 등록',unit:'건',target:10,actual:8,rule:'중복 제외 승인 DR',source:'엑셀 업로드'},{type:'부킹',unit:'K USD',target:100,actual:60,rule:'기간 내 확정된 부킹 · 취소 제외',source:'직접 입력'}]}];
let editing=-1;
const fmt=n=>Number(n).toLocaleString('ko-KR',{maximumFractionDigits:3});
const achieved=p=>p.goals.length>0&&p.goals.every(g=>g.actual>=g.target);
const ongoing=p=>p.start<='2026-09-23'&&p.end>='2026-09-23';
function render(){const count=promos.filter(ongoing).length,done=promos.filter(achieved).length;$('#promoSummary').innerHTML=`<small>프로모션 현황</small><div class="num">${count}<em>건 진행 중</em></div><p>전체 ${promos.length}건 중 목표 달성 ${done}건 · 복수 목표는 모두 충족 시 달성</p>`;
$('#promoCount').textContent=`진행 중 ${count}건 · 목표 달성 ${done}건`;
$('#promoCards').innerHTML=promos.map((p,i)=>`<article class="promo-card"><div class="row"><div><h3>${esc(p.name)}</h3><small>${esc(p.start)} — ${esc(p.end)}</small></div><button class="btn" data-edit="${i}">설정 변경</button></div><p><span class="tag ${achieved(p)?'good':''}">${achieved(p)?'목표 달성':ongoing(p)?'진행 중':'기간 외'}</span></p><div class="note"><b>보상 스킴</b><br>${esc(p.scheme||'미입력')}</div>${p.goals.map(g=>{const rate=g.actual/g.target*100;return `<div class="metric"><div class="row"><b>${esc(g.type)}</b><strong>${fmt(rate)}%</strong></div><div>${fmt(g.actual)} / ${fmt(g.target)} ${esc(g.unit)}</div><div class="progress"><span style="width:${Math.min(100,rate)}%"></span></div><small>인정 기준: ${esc(g.rule)}<br>입력 방식: ${esc(g.source)}${g.source==='직접 입력'?'':' (연결 예정)'}</small></div>`}).join('')}<small>달성 판정: 모든 목표 충족</small></article>`).join('');}
const opts=(arr,v)=>arr.map(x=>`<option${x===v?' selected':''}>${esc(x)}</option>`).join('');
function goalForm(g={type:'DR 등록',unit:'건',target:10,actual:0,rule:'기간 내 승인된 DR 기준',source:'직접 입력'}){const custom=!types.includes(g.type);return `<fieldset class="goal-form"><legend>성과 목표</legend><div class="form-grid"><label>목표 지표<select name="type">${opts(types,custom?'직접 입력':g.type)}</select></label><label>직접 입력 지표명<input name="custom" value="${custom?esc(g.type):''}" ${custom?'required':'disabled'} placeholder="예: PoC 완료"></label><label>단위<select name="unit">${opts(units,g.unit)}</select></label><label>목표<input name="target" type="number" min="0.001" step="any" required value="${g.target}"></label><label>실적<input name="actual" type="number" min="0" step="any" required value="${g.actual}"></label><label>입력 방식<select name="source">${opts(['직접 입력','엑셀 업로드','ERP 연동'],g.source)}</select></label><label class="wide">인정 기준<input name="rule" required value="${esc(g.rule)}"></label></div><button type="button" class="btn remove-goal">목표 삭제</button></fieldset>`;}
function open(i){editing=i;const p=i<0?{name:'',start:'2026-09-01',end:'2026-10-31',scheme:'',goals:[undefined]}:promos[i];$('#promoEditorTitle').textContent=i<0?'프로모션 추가':'프로모션 설정';const f=$('#promoForm');f.elements.name.value=p.name;f.elements.start.value=p.start;f.elements.end.value=p.end;f.elements.scheme.value=p.scheme;$('#goalForms').innerHTML=p.goals.map(goalForm).join('');$('#promoError').textContent='';$('#promoEditor').showModal();}
$('#promoCards').onclick=e=>{const b=e.target.closest('[data-edit]');if(b)open(+b.dataset.edit)};
$('#addPromo').onclick=()=>open(-1);$('#closePromo').onclick=()=>$('#promoEditor').close();
$('#addGoal').onclick=()=>$('#goalForms').insertAdjacentHTML('beforeend',goalForm());
$('#goalForms').onclick=e=>{if(e.target.closest('.remove-goal')){if($('#goalForms').children.length===1){$('#promoError').textContent='목표는 하나 이상 필요합니다.';return}e.target.closest('fieldset').remove();}};
$('#goalForms').onchange=e=>{if(e.target.name!=='type')return;const f=e.target.closest('fieldset'),type=e.target.value,custom=f.querySelector('[name=custom]');custom.disabled=type!=='직접 입력';custom.required=type==='직접 입력';if(presets[type]){f.querySelector('[name=unit]').value=presets[type][0];f.querySelector('[name=rule]').value=presets[type][1];}};
$('#promoForm').onsubmit=e=>{e.preventDefault();const f=e.target,goals=[...$('#goalForms').children].map(el=>{const get=n=>el.querySelector(`[name=${n}]`).value.trim();return {type:get('type')==='직접 입력'?get('custom'):get('type'),unit:get('unit'),target:+get('target'),actual:+get('actual'),rule:get('rule'),source:get('source')}});const p={name:f.elements.name.value.trim(),start:f.elements.start.value,end:f.elements.end.value,scheme:f.elements.scheme.value.trim(),goals};if(!p.name||p.end<p.start||goals.some(g=>!g.type||!g.rule||!Number.isFinite(g.target)||g.target<=0||!Number.isFinite(g.actual)||g.actual<0)){ $('#promoError').textContent='이름·기간·목표를 확인하세요. 종료일은 시작일 이후, 목표는 0보다 커야 합니다.';return;}if(editing<0)promos.push(p);else promos[editing]=p;render();$('#promoEditor').close();$('#promoStatus').textContent='예시에 적용했습니다. 새로고침하면 초기화되며 서버에는 저장되지 않습니다.';};
render();
})();
